export const CSS_VARIABLES = {
  "--top-nav-bar-height": "3.5rem",
  "--resume-control-bar-height": "3rem",
  "--resume-padding": "1.5rem",
  "--theme-navy": "#1b263b",
  "--theme-dark-navy": "#141c2f",
  "--theme-emerald": "#2a9d8f",
  "--theme-gold": "#e9c46a",
  "--theme-light-gray": "#f1f5f9",
  "--theme-black": "#0f172a",
  "--spacing-xs": "8px",
  "--spacing-sm": "12px",
  "--spacing-md": "16px",
  "--spacing-lg": "24px",
  "--spacing-xl": "32px",
} as const;